NPE when breaking crops with bare hands
java.lang.NullPointerException: Cannot invoke "net.minecraft.item.ItemStack.func_77973_b()" because "tool" is null
    at com.enderio.core.common.util.ToolUtil.damageDurability(ToolUtil.java:43)
    at com.enderio.core.common.handlers.RightClickCropHandler.handleCropRightClick(RightClickCropHandler.java:103)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_1300_RightClickCropHandler_handleCropRightClick_PlayerInteractEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100)
    at net.minecraft.server.management.ItemInWorldManager.activateBlockOrUseItem(ItemInWorldManager.java:353)
    at net.minecraft.network.NetHandlerPlayServer.processPlayerBlockPlacement(NetHandlerPlayServer.java:556)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.processPacket(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.processPacket(SourceFile:9)
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)